# Generated by Django 4.2.7 on 2026-01-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_hi',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
