# Generated by Django 4.2.7 on 2026-01-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0002_video_title_en_video_title_hi'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='description_hi',
            field=models.TextField(null=True),
        ),
    ]
