# Generated by Django 4.2.7 on 2026-02-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0003_video_description_en_video_description_hi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='moment',
            options={'verbose_name': 'Moment', 'verbose_name_plural': 'Moments'},
        ),
        migrations.AlterModelOptions(
            name='podcast',
            options={'verbose_name': 'Podcast', 'verbose_name_plural': 'Podcasts'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
