# Generated by Django 4.2.7 on 2026-02-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0004_alter_article_options_alter_moment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='moment',
            name='description_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='moment',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='moment',
            name='title_hi',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
